### ISSUE TITLE
Read and write data on the new thread

### ISSUE THREAD

**Issue by jin123d** [Guilherme-HRamos/Easy-Save#1]
Function is a bit simple, it is recommended to read and write data on the new thread

**Comment by Guilherme-HRamos** [comment]
Yes! its my next step (I forgot to write this on my readme, sorry)... I'll work on that, but if you wanna help... be my guest ;)

**Comment by Guilherme-HRamos** [comment]
I did some tests here, but I guess the code usability will be boring, with some callbacks caused by inner classes (I used runnable in my tests)... Create an async task when we're using the lib could be better, no?

**Comment by jin123d** [comment]
@Guilherme-HRamos Maybe I have time to submit a pull request tomorrow:grinning::grinning:

**Comment by Guilherme-HRamos** [comment]
added save and load async feature
