### ISSUE TITLE
How to clear the cache?

### ISSUE THREAD

**Issue by pooja-gaikwad15** [Guilherme-HRamos/Easy-Save#4]
Couldn't find any resource as to how to clear the cache or delete a key?

**Comment by android-guilherme** [comment]
Hello,

You can set a null save...

Like "...saveModel("key", null);"

Em seg, 8 de out de 2018 03:38, Pooja Gaikwad <notifications@github.com>
escreveu:

**Comment by pooja-gaikwad15** [comment]
What if I wish to clear all the cached data?

**Comment by android-guilherme** [comment]
The data will be cleared too...

Em qui, 11 de out de 2018 07:29, Pooja Gaikwad <notifications@github.com>
escreveu:
